[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "hugo  --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.54.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.tech] # 'staging' is a branch name
command = "hugo --gc --minify"
base = "tech"

[context.tech.environment]
HUGO_ENV = "tech"
HUGO_VERSION = "0.54.0"
HUGO_ENABLEGITINFO = "true"
